### ISSUE TITLE
Ability to open html notebooks in the browser instead of downloading?

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/SimpleDifferentialOperators.jl#199] opened 2019-06-05 23:35 UTC
See https://quantecon.github.io/SimpleDifferentialOperators.jl/stable/notebooks/

All of the links require a download.  Is there any way to have them open in a browser instead?  See https://github.com/QuantEcon/SimpleDifferentialOperators.jl/releases/download/v0.6.1/KFE.html for example.

**Comment by arnavs** [comment] 2019-06-17 19:59
Unfortunately need to close this as impossible. 

* For PDFs (if you had issues with them), the solution is a browser setting (open PDFs in-browser, vs downloading.) We can include a short note about that in the docs somewhere, if you think it'll help.

* For `.ipynb`, the issue is that instead of linking to a position in a GitHub repository (where notebooks displayed using whatever backend skullduggery GitHub uses to render), we're linking to actual, static files associated with a release. There's no way around it without upending the whole Travis+Releases setup.

**Comment by arnavs** [comment] 2019-06-17 20:02
* Actually... on second thought, we might try feeding the links to the static `.ipynb` files to `nbviewer`. Not sure how this would work in the context of our internal documentation links. But we could play around with it; [this](https://github.com/QuantEcon/SimpleDifferentialOperators.jl/releases/download/v0.6.1/LCP_advanced.ipynb) works, for example.

Probably low priority for now, though.

**Comment by jlperla** [comment] 2019-06-17 20:11
Focus on the HTML, which is the biggest issue. Why does that download instead of go to a page? Is there any way around that?

**Comment by jlperla** [comment] 2019-06-17 20:14
The issue with the HTML could be dealt with if you could get nbviewer working.  ipynb and pdfs are ok to download if there is no other way.  But at this point, there is no way at all to browse the generated notebooks on the web..  We need to find a solution or change how the builds work.

**Comment by arnavs** [comment] 2019-06-19 17:27
Turns out that `nbviewer` is the easiest approach; `htmlgitpreview` would've worked, but there's a redirect from the link we're shown in the release. 

The actual modification is pretty simple; just replace `https://github.com/` with the `https://nbviewer.jupyter.org/urls/github.com/`

**Closed by arnavs** 2019-06-19 17:27 UTC
